import { notFound } from "next/navigation";
import Link from "next/link";
import { db, getJudgment } from "@/lib/db";
import { addNote } from "@/lib/actions";
import StatusBadge from "@/components/StatusBadge";
import { attributionLabels, decisionLabels, outcomeLabels, type Attribution, type Outcome } from "@/lib/types";
export const dynamic="force-dynamic";
export default async function DetailPage({params}:{params:Promise<{id:string}>}){const {id}=await params;const row=getJudgment(id);if(!row)notFound();const notes=db.prepare("SELECT * FROM judgment_notes WHERE judgment_id=? ORDER BY created_at DESC").all(id) as {id:string;content:string;created_at:string}[];const review=db.prepare("SELECT * FROM reviews WHERE judgment_id=?").get(id) as Record<string,unknown>|undefined;const noteAction=addNote.bind(null,id);
return <><header className="page-head"><div><h1>{row.symbol}</h1><div className="muted">创建于 {row.created_at.slice(0,16).replace("T"," ")} · 原始判断不可覆盖</div></div><div><StatusBadge row={row}/> {!review&&<Link className="button primary" href={`/judgments/${id}/review`}>填写复盘</Link>}</div></header>
<div className="facts"><div className="fact"><span>决策</span>{decisionLabels[row.decision]}</div><div className="fact"><span>信心度</span>{row.confidence}%</div><div className="fact"><span>验证周期</span>{row.judgment_date} → {row.due_date}</div><div className="fact"><span>资产类型</span>{row.asset_type}</div></div>
<section className="panel"><div className="panel-head"><h2>原始判断</h2><span className="badge">永久保留</span></div><div className="timeline"><article className="timeline-item"><div className="timeline-time">判断逻辑</div><p className="prose">{row.thesis}</p><div className="timeline-time">支持证据</div><p className="prose">{row.evidence}</p>{(row.reference_price||row.benchmark||row.tags)&&<div className="muted">参考价格：{row.reference_price??"—"}　基准：{row.benchmark??"—"}　标签：{row.tags??"—"}</div>}</article>{notes.map(n=><article className="timeline-item" key={n.id}><div className="timeline-time">追加备注 · {n.created_at.slice(0,16).replace("T"," ")}</div><p className="prose">{n.content}</p></article>)}</div>
<form action={noteAction}><div className="field"><label htmlFor="content">追加备注</label><textarea className="form-control" name="content" id="content" placeholder="记录新证据或想法变化；不会修改原始判断" required/></div><div className="actions"><button className="button" type="submit">追加备注</button></div></form></section>
{review&&<section className="panel"><div className="panel-head"><h2>复盘结果</h2><span className="badge done">{outcomeLabels[review.outcome as Outcome]}</span></div><div className="facts"><div className="fact"><span>实际收益</span>{review.actual_return==null?"—":`${review.actual_return}%`}</div><div className="fact"><span>基准收益</span>{review.benchmark_return==null?"—":`${review.benchmark_return}%`}</div><div className="fact"><span>超额收益</span>{review.excess_return==null?"—":`${review.excess_return}%`}</div><div className="fact"><span>主要归因</span>{attributionLabels[review.attribution as Attribution]}</div></div><h2>结果</h2><p className="prose">{String(review.result_summary)}</p><h2>归因</h2><p className="prose">{String(review.result_reason)}</p><div className="muted">原判断是否成立：{String(review.original_thesis_valid)}</div><h2>学习</h2><p className="prose">判断对了：{String(review.right_points)}\n\n判断错了：{String(review.wrong_points)}\n\n下次改进：{String(review.next_change)}{review.new_rule?`\n\n新规则：${review.new_rule}`:""}</p></section>}</>}
