import Link from "next/link";
import { listJudgments } from "@/lib/db";
import { statusOf } from "@/lib/types";
export const dynamic="force-dynamic";
const avg=(xs:number[])=>xs.length?xs.reduce((a,b)=>a+b,0)/xs.length:null;
export default function Dashboard(){const rows=listJudgments();const reviewed=rows.filter(r=>r.outcome);const binary=reviewed.filter(r=>r.outcome==="correct"||r.outcome==="incorrect");const correct=binary.filter(r=>r.outcome==="correct").length;const pending=rows.filter(r=>statusOf(r)==="待复盘");const active=rows.filter(r=>statusOf(r)==="验证中");const returns=reviewed.map(r=>r.actual_return).filter((x):x is number=>x!=null);const excess=reviewed.map(r=>r.excess_return).filter((x):x is number=>x!=null);const bins=[[0,49],[50,59],[60,69],[70,79],[80,89],[90,100]].map(([lo,hi])=>{const sample=binary.filter(r=>r.confidence>=lo&&r.confidence<=hi);const wins=sample.filter(r=>r.outcome==="correct").length;return{label:`${lo}–${hi}%`,n:sample.length,rate:sample.length?Math.round(wins/sample.length*100):null}});const fmt=(n:number|null)=>n==null?"—":`${n>=0?"+":""}${n.toFixed(1)}%`;
return <><header className="page-head"><div><h1>数据看板</h1><div className="muted">看清判断质量，而不只是盈亏。</div></div><Link className="button primary" href="/judgments/new">＋ 新建判断</Link></header><section className="stats"><div className="stat"><div className="stat-label">总判断数</div><div className="stat-value">{rows.length}</div></div><div className="stat"><div className="stat-label">验证中</div><div className="stat-value">{active.length}</div></div><div className="stat"><div className="stat-label">已复盘</div><div className="stat-value">{reviewed.length}</div></div><div className="stat"><div className="stat-label">判断正确率</div><div className="stat-value">{binary.length?Math.round(correct/binary.length*100)+"%":"—"}</div><div className="stat-note">仅统计正确 / 错误</div></div><div className="stat"><div className="stat-label">平均信心度</div><div className="stat-value">{rows.length?Math.round(avg(rows.map(r=>r.confidence))!)+"%":"—"}</div></div><div className="stat"><div className="stat-label">平均收益</div><div className="stat-value positive">{fmt(avg(returns))}</div></div><div className="stat"><div className="stat-label">平均超额收益</div><div className="stat-value positive">{fmt(avg(excess))}</div></div></section>
<div className="dashboard-grid"><section className="panel"><div className="panel-head"><h2>信心度校准</h2><span className="muted">真实正确率</span></div><div className="calibration">{bins.map(b=><div className="cal-row" key={b.label}><span>{b.label}</span><span>{b.n} 条</span><div className="bar"><span style={{width:`${b.rate??0}%`}}/></div><strong>{b.rate==null?"—":b.rate+"%"}</strong></div>)}</div></section><section className="panel"><div className="panel-head"><h2>待复盘</h2><Link className="muted" href="/reviews">查看全部 →</Link></div>{pending.slice(0,5).map(r=><div className="review-row" key={r.id}><div><div className="review-title">{r.symbol}</div><div className="review-thesis">{r.thesis}</div></div><Link className="button" href={`/judgments/${r.id}/review`}>复盘</Link></div>)}{!pending.length&&<div className="empty">暂无待复盘记录</div>}</section></div>
<section className="panel"><div className="panel-head"><h2>本地数据</h2><span className="muted">建议定期导出备份</span></div><div className="toolbar"><a className="button" href="/api/export?format=json">导出 JSON</a><a className="button" href="/api/export?format=csv">导出 CSV</a></div></section></>}
